-- Stored Procedures cho TaiKhoan
USE QuanLyCuaHangDongHo;
GO

-- 1. InsertTaiKhoan
CREATE PROCEDURE InsertTaiKhoan
    @MNV INT,
    @TDN NVARCHAR(255),
    @MK NVARCHAR(255),
    @MNQ INT,
    @TT INT
AS
BEGIN
    INSERT INTO TAIKHOAN (MNV, TDN, MK, MNQ, TRANGTHAI) 
    VALUES (@MNV, @TDN, @MK, @MNQ, @TT)
END
GO

-- 2. UpdateTaiKhoan
CREATE PROCEDURE UpdateTaiKhoan
    @TDN NVARCHAR(255),
    @TT INT,
    @MNQ INT,
    @MNV INT
AS
BEGIN
    UPDATE TAIKHOAN 
    SET TDN = @TDN, TRANGTHAI = @TT, MNQ = @MNQ 
    WHERE MNV = @MNV
END
GO

-- 3. DeleteTaiKhoan
CREATE PROCEDURE DeleteTaiKhoan
    @MNV INT
AS
BEGIN
    UPDATE TAIKHOAN 
    SET TRANGTHAI = -1 
    WHERE MNV = @MNV
END
GO

-- 4. GetAllTaiKhoan
CREATE PROCEDURE GetAllTaiKhoan
AS
BEGIN
    SELECT * FROM TAIKHOAN 
    WHERE TRANGTHAI IN (0, 1, 2)
END
GO

-- 5. GetTaiKhoanByMNV
CREATE PROCEDURE GetTaiKhoanByMNV
    @MNV NVARCHAR(MAX)
AS
BEGIN
    SELECT * FROM TAIKHOAN 
    WHERE MNV = CAST(@MNV AS INT)
END
GO

-- 6. GetTaiKhoanByUser
CREATE PROCEDURE GetTaiKhoanByUser
    @TDN NVARCHAR(255)
AS
BEGIN
    SELECT * FROM TAIKHOAN 
    WHERE TDN = @TDN
END
GO

-- 7. GetTaiKhoanByEmail
CREATE PROCEDURE GetTaiKhoanByEmail
    @EMAIL NVARCHAR(255)
AS
BEGIN
    SELECT TK.* FROM TAIKHOAN TK 
    JOIN NHANVIEN NV ON TK.MNV = NV.MNV 
    WHERE NV.EMAIL = @EMAIL
END
GO

-- 8. UpdateTTCXL
CREATE PROCEDURE UpdateTTCXL
    @EMAIL NVARCHAR(255)
AS
BEGIN
    UPDATE TAIKHOAN 
    SET TRANGTHAI = 2 
    FROM TAIKHOAN TK
    JOIN NHANVIEN NV ON TK.MNV = NV.MNV 
    WHERE NV.EMAIL = @EMAIL
END
GO

-- 9. UpdatePasswordByEmail
CREATE PROCEDURE UpdatePasswordByEmail
    @MK NVARCHAR(255),
    @EMAIL NVARCHAR(255)
AS
BEGIN
    UPDATE TAIKHOAN 
    SET MK = @MK 
    FROM TAIKHOAN TK
    JOIN NHANVIEN NV ON TK.MNV = NV.MNV 
    WHERE NV.EMAIL = @EMAIL
END
GO

-- 10. UpdatePasswordByMNV
CREATE PROCEDURE UpdatePasswordByMNV
    @MNV INT,
    @MK NVARCHAR(255)
AS
BEGIN
    UPDATE TAIKHOAN 
    SET MK = @MK 
    WHERE MNV = @MNV
END
GO

-- 11. SendOTP
CREATE PROCEDURE SendOTP
    @OTP NVARCHAR(255),
    @EMAIL NVARCHAR(255)
AS
BEGIN
    UPDATE TAIKHOAN 
    SET OTP = @OTP 
    FROM TAIKHOAN TK
    JOIN NHANVIEN NV ON TK.MNV = NV.MNV 
    WHERE NV.EMAIL = @EMAIL
END
GO

-- 12. CheckOTP
CREATE PROCEDURE CheckOTP
    @EMAIL NVARCHAR(255),
    @OTP NVARCHAR(255)
AS
BEGIN
    SELECT TK.* FROM TAIKHOAN TK 
    JOIN NHANVIEN NV ON TK.MNV = NV.MNV 
    WHERE NV.EMAIL = @EMAIL AND TK.OTP = @OTP
END
GO
